[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run app/main.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
PYTHON_VERSION = "3.11"
