[theme]
# Modern gradient primary color (Purple)
primaryColor = "#7C3AED"
# Clean white background
backgroundColor = "#FFFFFF"
# Subtle gray for secondary backgrounds
secondaryBackgroundColor = "#F9FAFB"
# Dark text for readability
textColor = "#111827"
# Modern font stack with Inter as primary
font = "sans serif"

[server]
maxUploadSize = 500
# Disable CORS and XSRF for cloud deployment compatibility
enableCORS = false
enableXsrfProtection = false
# Enable file watcher for hot reload (local dev only)
fileWatcherType = "auto"
# Headless mode for deployment
headless = true
# Allow connections from any host
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[client]
# Improve performance
toolbarMode = "minimal"
showErrorDetails = true